/** 待办模块中文文案；沿用 sltool 的待办与通用操作文案，不引入 i18n 依赖。 */
export const todoTexts = {
  search: "搜索待办...",
  today: "今日",
  pending: "未完成",
  inProgress: "进行中",
  completed: "已完成",
  newTask: "新建待办",
  editTask: "编辑待办",
  customerPlaceholder: "客户名或事项，可留空",
  titlePlaceholder: "待办事项",
  receivedAtPlaceholder: "接收时间",
  dueAtPlaceholder: "完成时间",
  notePlaceholder: "备注",
  empty: "暂无",
  noCustomer: "未填写来源",
  start: "开始",
  rollback: "撤回",
  restore: "撤回",
  complete: "完成",
  defer: "延期",
  urgent: "急",
  markUrgent: "加急",
  unmarkUrgent: "取消加急",
  confirmDeleteMessage: "删除后无法恢复。",
  viewScreenshots: "查看截图",
  previewFailed: "截图预览失败",
  recognizeClipboard: "识别剪贴板",
  recognizingClipboard: "正在识别剪贴板...",
  recognizeClipboardSuccess: "识别成功",
  recognizeClipboardFailure: "识别失败",
  localRecognized: "已读取内容",
  noClipboardContent: "没有可用内容",
  cancel: "取消",
  save: "保存",
  delete: "删除",
  close: "关闭",
  retry: "重试",
  loadFailed: "加载待办失败，请重试。",
  saveFailed: "保存失败",
  clipboardNoImage: "剪贴板没有图片",
  addAttachmentFailed: "添加截图失败",
  savingLabel: "保存中...",
  deletingLabel: "删除中...",
  actionBusy: "正在处理，请稍候",
  addAttachment: "添加截图",
  previewAttachment: (index: number) => `预览截图 ${index + 1}`,
  removeAttachment: (index: number) => `删除截图 ${index + 1}`,
  closePreview: "关闭截图预览",
  loadMore: (count: number) => `显示更多 ${count} 条`,
  customerLabel: "客户或来源",
  titleLabel: "待办事项",
  noteLabel: "备注",
} as const;

/** 服务 Error.message 可读时直接展示，否则退回默认文案。 */
export function readableTodoError(error: unknown, fallback: string) {
  if (error instanceof Error && error.message.trim()) return error.message;
  if (typeof error === "string" && error.trim()) return error;
  return fallback;
}
